# Offense count: 1
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Exclude:
    - 'example/fact.rb'

# Offense count: 3
Lint/HandleExceptions:
  Exclude:
    - 'lib/libhoney/client.rb'
    - 'lib/libhoney/transmission.rb'

# Offense count: 2
Lint/RescueException:
  Exclude:
    - 'example/fact.rb'
    - 'lib/libhoney/transmission.rb'

# Offense count: 6
Metrics/AbcSize:
  Max: 45

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 27

# Offense count: 2
Metrics/CyclomaticComplexity:
  Max: 8

# Offense count: 6
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 43

# Offense count: 2
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 12

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 8
