version: 2.0

rubocop_steps: &rubocop_steps
  - checkout
  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  - run:
      name: install dependencies
      command: |
        bundle install --jobs=4 --retry=3 --path vendor/bundle
  - save_cache:
      paths:
        - ./vendor/bundle
      key: v1-dependencies-{{ checksum "Gemfile.lock" }}
  - run:
      name: run rubocop
      command: bundle exec rake rubocop


test_steps: &test_steps
  - checkout
  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  - run:
      name: install dependencies
      command: |
        bundle install --jobs=4 --retry=3 --path vendor/bundle
  - save_cache:
      paths:
        - ./vendor/bundle
      key: v1-dependencies-{{ checksum "Gemfile.lock" }}
  - run:
      name: run tests
      command: bundle exec rake test


jobs:
  ruby-2.3-test:
    docker:
      - image: circleci/ruby:2.3
    steps:
      *test_steps
  ruby-2.3-rubocop:
    docker:
      - image: circleci/ruby:2.3
    steps:
      *rubocop_steps
  ruby-2.4-test:
    docker:
      - image: circleci/ruby:2.4
    steps:
      *test_steps
  ruby-2.4-rubocop:
    docker:
      - image: circleci/ruby:2.4
    steps:
      *rubocop_steps
  ruby-2.5-test:
    docker:
      - image: circleci/ruby:2.5
    steps:
      *test_steps
  ruby-2.5-rubocop:
    docker:
      - image: circleci/ruby:2.5
    steps:
      *rubocop_steps
  ruby-2.6-test:
    docker:
      - image: circleci/ruby:2.6
    steps:
      *test_steps
  ruby-2.6-rubocop:
    docker:
      - image: circleci/ruby:2.6
    steps:
      *rubocop_steps


workflows:
  version: 2
  build:
    jobs:
      - ruby-2.3-test
      - ruby-2.3-rubocop
      - ruby-2.4-test
      - ruby-2.4-rubocop
      - ruby-2.5-test
      - ruby-2.5-rubocop
      - ruby-2.6-test
      - ruby-2.6-rubocop


# jobs:
#   build:
#     docker:
#       - image: circleci/ruby:2.4.1-node-browsers

#     working_directory: ~/repo

#     steps:
#       - checkout

#       # Download and cache dependencies
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "Gemfile.lock" }}
#             # fallback to using the latest cache if no exact match is found
#             - v1-dependencies-

#       - run:
#           name: install dependencies
#           command: |
#             bundle install --jobs=4 --retry=3 --path vendor/bundle

#       - save_cache:
#           paths:
#             - ./vendor/bundle
#           key: v1-dependencies-{{ checksum "Gemfile.lock" }}

#       # run tests!
#       - run:
#           name: run rubocop
#           command: bundle exec rake rubocop
#       - run:
#           name: run tests
#           command: bundle exec rake test

