version: 2.0

test_steps: &test_steps
  - checkout
  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  - run:
      name: install dependencies
      command: |
        bundle install --jobs=4 --retry=3 --path vendor/bundle
  - save_cache:
      paths:
        - ./vendor/bundle
      key: v1-dependencies-{{ checksum "Gemfile.lock" }}
  - run:
      name: run rubocop
      command: bundle exec rake rubocop
  - run:
      name: run tests
      command: bundle exec rake test


jobs:
  ruby-2.3:
    docker:
      - image: circleci/ruby:2.3
    steps: *test_steps
  ruby-2.4:
    docker:
      - image: circleci/ruby:2.4
    steps: *test_steps
  ruby-2.5:
    docker:
      - image: circleci/ruby:2.5
    steps: *test_steps
  ruby-2.6:
    docker:
      - image: circleci/ruby:2.6
    steps: *test_steps


workflows:
  version: 2
  build:
    jobs:
      - ruby-2.3
      - ruby-2.4
      - ruby-2.5
      - ruby-2.6

